- name: install httpd package (RedHat)
  tags: apache,rhel,httpd
  yum:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "RedHat"

  # Start httpd service on RHEL
- name: start and enable httpd (RedHat)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: install apache2 package (Ubuntu)
  tags: apache,ubuntu,httpd
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

# Copy file from a directory to other
- name: copy default html file for site
  tags: apache,apache2,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644