# Install httpd on RedHat  
- name: install httpd package (RedHat)
  tags: apache,rhel,httpd
  yum:
    name:
      - "{{  apache_package_name  }}"
      - "{{  php_package_name  }}"
    state: latest
  when: ansible_distribution == "RedHat"

  # Start httpd service on RedHat
- name: start and enable httpd (RedHat)
  tags: apache,centos,httpd
  service:
    name: "{{  apache_service  }}"
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

# Install Apache2 on Ubuntu
- name: install apache2 package (Ubuntu)
  tags: apache,ubuntu,httpd
  apt:
    name:
      - "{{  apache_package_name  }}"
      - "{{  php_package_name  }}"
    state: latest
  when: ansible_distribution == "Ubuntu"

# Copy file HTML file to each web server
- name: copy default html file for site
  tags: apache,apache2,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644