---

- hosts: all
  become: true
  pre_tasks:
# Pre Tasks - to check the update on each VM.
  - name: install updates (RedHat)    # Name to display when the playbook runs
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"    # Where to run this section

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:

  - name: install httpd package (RedHat)
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install apache2 package (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

# Tasks based on groups defined in inventory
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb server package (RedHat)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb server
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
