# User key added
- name: add ssh key for alpha
  tags: always
  authorized_key:
    user: alpha
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILYzaKsIpIxMxypOkNommg53oSWCkZhxWa+40NYVpn6T ansible"
    